
version: '3.8'

services:

  todo:
    image: gregdocker82/todo-docker
    ports:
     - 8080:8080
    environment:
     - POSTGRES_HOST=db

  db:
    image: postgres
    restart: always
    ports:
     - 5432:5432
    environment:
     - POSTGRES_PASSWORD=postgres